In [ ]:
%reset -f

In [2]:
## 1) 행렬 정의

import numpy as np

# 두 개의 2차원 행렬을 정의
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


In [3]:
## 2) 원소 연산

# 원소별 덧셈
addition = A + B

# 원소별 뺄셈
subtraction = A - B

# 원소별 곱셈
elementwise_multiplication = A * B

# 원소별 나눗셈
division = A / B

print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Element-wise Multiplication:\n", elementwise_multiplication)
print("Division:\n", division)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Element-wise Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [4]:
## 3) 행렬 연산

# 행렬 곱 (Dot Product)
dot_product = np.dot(A, B)
# 또는
dot_product = A @ B

print("Dot Product:\n", dot_product)

# 원소별 제곱
squared_elements = A ** 2

print("Squared Elements:\n", squared_elements)

# 행렬의 제곱 (행렬 곱으로)
matrix_squared = np.dot(A, A)
# 또는
matrix_squared = A @ A

print("Matrix Squared:\n", matrix_squared)


Dot Product:
 [[19 22]
 [43 50]]
Squared Elements:
 [[ 1  4]
 [ 9 16]]
Matrix Squared:
 [[ 7 10]
 [15 22]]


In [10]:
## 4) 영행렬, 일행렬, 단위행렬

import numpy as np

# 3x3 영행렬
zero_matrix = np.zeros((3, 3))
print("Zero Matrix:\n", zero_matrix)

# 3x3 일행렬
ones_matrix = np.ones((3, 3))
print("Ones Matrix:\n", ones_matrix)

# 3x3 단위행렬
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)


Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
## 5) 랜덤 함수

import numpy as np

# Random Seed
np.random.seed() # 랜덤 시드 설정

# Uniform Random Variable
random_integers = np.random.randint(low=1, high=10, size=5) # 1 이상 10 미만의 랜덤 정수 5개
print("Random Integers:", random_integers)

random_floats = np.random.uniform(low=0.0, high=1.0, size=5) # 0.0 이상 1.0 미만의 랜덤 실수 5개
print("Random Floats:", random_floats)

# Binomial Random Variable
binomial_distribution = np.random.binomial(n=10, p=0.5, size=5) # 시행 횟수 10, 성공 확률 0.5인 이항 분포에서 5개 추출
print("Binomial Distribution:", binomial_distribution)

# Normal Random Variable
standard_normal = np.random.standard_normal(size=5)               # 평균 0, 표준편차 1의 표준 정규 분포에서 5개 추출
print("Standard Normal:", standard_normal)

normal_distribution = np.random.normal(loc=0.0, scale=1.0, size=5) # 평균(loc) 0, 표준편차(scale) 1의 정규 분포에서 5개 추출
print("Normal Distribution:", normal_distribution)

# Poisson Random Variable
poisson_distribution = np.random.poisson(lam=3.0, size=5) # 평균 발생 빈도(lam)가 3인 포아송 분포에서 5개 추출
print("Poisson Distribution:", poisson_distribution)

# Exponential Random Variable
exponential_distribution = np.random.exponential(scale=1.0, size=5) # 스케일(scale) 파라미터가 1인 지수 분포에서 5개 추출
print("Exponential Distribution:", exponential_distribution)


Random Integers: [3 2 9 3 1]
Random Floats: [0.96392367 0.76461408 0.5219752  0.8352376  0.99267348]
Binomial Distribution: [2 4 4 6 8]
Standard Normal: [ 0.37515916  0.39081378  0.44951266  1.48564241 -0.20604604]
Normal Distribution: [-0.99647029  0.1959049  -0.83063404  0.27300354 -0.1763417 ]
Poisson Distribution: [2 1 4 3 1]
Exponential Distribution: [2.3259944  0.75184347 1.8344832  0.36041739 2.27149323]
